### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by aliudurim** [Keelar/ExprK#6]
Hi
Is it possible to define string expression:

e.g: 
expressions.define("x", "durim")

**Comment by Keelar** [comment]
I don't think I understand the question? You can do what you did in your example if "durim" was previously defined.

**Comment by aliudurim** [comment]
Hi Keelar
Sorry for the improper explanation but the situation is this: 
I have an array with key, value pair and I'm trying to define variables:

e.g
vars.forEachIndexed { key, value -> 
      expressions.define(key, value)
}
In the example above the value, it can be Int, Double, String.
In my case String not worked, you can see the error in the screenshot.
Hope this time I was clearer.

![Screen Shot 2019-11-12 at 2 09 44 PM](https://user-images.githubusercontent.com/12698441/68674844-f2612300-0556-11ea-901b-c60486aa6e34.png)

**Comment by Keelar** [comment]
The string version of the define function expects the string to be a mathematical expression, so you can't just assign variables to arbitrary strings. ExprK is a mathematical expression evaluator, so strings as values don't really make any sense in the context of this library since all expressions must produce a numerical value and strings don't really have a numerical value.

Hopefully that answers your question.
